#!/usr/bin/env bash
# Toggle: Ctrl+W tiling layer (hold Ctrl+W then H/J/K/L to tile)
# Requires: xremap, wmctrl, xdpyinfo (X11)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../../../" && pwd)"
CONFIG_PATH="$HOME/.config/xremap-tiling.yml"
PID_FILE="$HOME/.config/xremap-tiling.pid"
STATE_FILE="$HOME/.config/tiling-control-w-enabled"
LOG_FILE="$HOME/.config/xremap-tiling.log"

ensure_tools() {
  for bin in xremap wmctrl xdpyinfo; do
    if ! command -v "$bin" >/dev/null 2>&1; then
      echo "Error: '$bin' is required but not installed" >&2
      exit 1
    fi
  done
}

write_config() {
  mkdir -p "$(dirname "$CONFIG_PATH")"
  cat > "$CONFIG_PATH" <<YAML
# Auto-generated by control-w-tiling.sh
keymap:
  - name: 'Ctrl+W tiling layer'
    remap:
      Ctrl-w-h: { launch: ["bash", "-lc", "$ROOT_DIR/scripts/tiling-move.sh left"] }
      Ctrl-w-l: { launch: ["bash", "-lc", "$ROOT_DIR/scripts/tiling-move.sh right"] }
      Ctrl-w-k: { launch: ["bash", "-lc", "$ROOT_DIR/scripts/tiling-move.sh up"] }
      Ctrl-w-j: { launch: ["bash", "-lc", "$ROOT_DIR/scripts/tiling-move.sh down"] }
      Ctrl-w-f: { launch: ["bash", "-lc", "$ROOT_DIR/scripts/tiling-move.sh full"] }
YAML
}

start() {
  ensure_tools
  write_config

  # Stop existing if any
  stop || true

  nohup xremap "$CONFIG_PATH" >"$LOG_FILE" 2>&1 &
  echo $! > "$PID_FILE"
  sleep 0.2
  if [[ -s "$PID_FILE" ]] && ps -p "$(cat "$PID_FILE")" >/dev/null 2>&1; then
    touch "$STATE_FILE"
    echo "✓ Ctrl+W tiling layer ENABLED"
  else
    echo "Error: Failed to start xremap for tiling. See $LOG_FILE" >&2
    exit 1
  fi
}

stop() {
  if [[ -f "$PID_FILE" ]]; then
    PID=$(cat "$PID_FILE" 2>/dev/null || echo "")
    if [[ -n "${PID}" ]] && ps -p "$PID" >/dev/null 2>&1; then
      kill "$PID" || true
    fi
    rm -f "$PID_FILE"
  fi
  rm -f "$STATE_FILE"
  echo "✓ Ctrl+W tiling layer DISABLED"
}

status() {
  if [[ -f "$STATE_FILE" ]]; then
    echo "ENABLED"
  else
    echo "DISABLED"
  fi
}

case "${1:-toggle}" in
  on|enable) start ;;
  off|disable) stop ;;
  toggle)
    if [[ -f "$STATE_FILE" ]]; then
      stop
    else
      start
    fi
    ;;
  status) status ;;
  *)
    echo "Usage: $0 {on|off|toggle|status}" >&2
    exit 1
    ;;
esac
